// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoH1U2mFHfLvbWwu0GtqdpIxaM-L0-0QE',
    appId: '1:640267146973:web:290c410ec992cbd569ad34',
    messagingSenderId: '640267146973',
    projectId: 'sensyapp-ab595',
    authDomain: 'sensyapp-ab595.firebaseapp.com',
    storageBucket: 'sensyapp-ab595.firebasestorage.app',
    measurementId: 'G-EJVJTF7TCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2BtAJpC3OZ3t4hp53Spbp59mImiBC1-U',
    appId: '1:640267146973:android:2c30e15b9149a87269ad34',
    messagingSenderId: '640267146973',
    projectId: 'sensyapp-ab595',
    storageBucket: 'sensyapp-ab595.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbVmLEe_yTZF8l4IrX52jWExQPRffDew0',
    appId: '1:640267146973:ios:0340c4f367288f3969ad34',
    messagingSenderId: '640267146973',
    projectId: 'sensyapp-ab595',
    storageBucket: 'sensyapp-ab595.firebasestorage.app',
    iosBundleId: 'com.example.sensyClinicianApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbVmLEe_yTZF8l4IrX52jWExQPRffDew0',
    appId: '1:640267146973:ios:0340c4f367288f3969ad34',
    messagingSenderId: '640267146973',
    projectId: 'sensyapp-ab595',
    storageBucket: 'sensyapp-ab595.firebasestorage.app',
    iosBundleId: 'com.example.sensyClinicianApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoH1U2mFHfLvbWwu0GtqdpIxaM-L0-0QE',
    appId: '1:640267146973:web:2fd8ea056d528ece69ad34',
    messagingSenderId: '640267146973',
    projectId: 'sensyapp-ab595',
    authDomain: 'sensyapp-ab595.firebaseapp.com',
    storageBucket: 'sensyapp-ab595.firebasestorage.app',
    measurementId: 'G-2Z3JXZEEJV',
  );

}